version: "3.8"
services:
  klipper:
    image: dawei06/klipper
    cap_add:
    - SYS_RAWIO
    devices:
    - /dev/ttyS5:/dev/dc-printer
    - /dev/gpiochip1:/dev/gpiochip1
    volumes:
    - "configs:/opt/cfg"
    restart: always
  
  mainsail:
    image: dawei06/mainsail
    ports:
      - 80:80
    restart: always

volumes:
  configs:
    name: klipper-configs
